### ISSUE TITLE
Error with Java 8

### ISSUE THREAD

**Issue by ghost** [dr3plus/dr3#8]
Hello,

I've error with java 8, obtain error : XML.

Error loading drftpd
org.drftpd.usermanager.UserFileException: Error loading drftpd
    at org.drftpd.usermanager.javabeans.BeanUserManager.getUserByNameUnchecked(BeanUserManager.java:109)
    at org.drftpd.usermanager.AbstractUserManager.getUserByNameIncludeDeleted(AbstractUserManager.java:179)
    at org.drftpd.commands.login.LoginHandler.doUSER(LoginHandler.java:196)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.drftpd.commandmanager.StandardCommandManager.execute(StandardCommandManager.java:203)
    at org.drftpd.master.BaseFtpConnection$CommandThread.run(BaseFtpConnection.java:611)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Caused by: org.drftpd.usermanager.UserFileException: Error loading drftpd
    at org.drftpd.usermanager.javabeans.BeanUserManager.loadUser(BeanUserManager.java:135)
    at org.drftpd.usermanager.javabeans.BeanUserManager.getUserFromSoftReference(BeanUserManager.java:165)
    at org.drftpd.usermanager.javabeans.BeanUserManager.getUserByNameUnchecked(BeanUserManager.java:104)
    ... 11 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
    at java.beans.XMLDecoder.readObject(Unknown Source)
    at org.drftpd.usermanager.javabeans.BeanUserManager.loadUser(BeanUserManager.java:128)
    ... 13 more

Thx!

**Comment by ghost** [comment]
https://github.com/drftpd-ng/drftpd3/issues/4
